name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/html/BackendDeveloper2024
            git pull origin main
            cd algebra-laravel-ispit
            composer install --no-dev --prefer-dist --no-progress --no-scripts
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
