name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 4: Deploy changes to the server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          # Prepare SSH connection
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Navigate to the server directory and pull the latest changes
          ssh -i ~/.ssh/id_rsa $USER@$HOST << EOF
            cd /var/www/html/BackendDeveloper2024
     
            git reset --hard
            git clean -df
          
            git pull origin main
            cd algebra-laravel-ispit
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
          EOF
