name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' # Adjust to your PHP version
          tools: composer, phpunit, phpstan

      - name: Navigate to Project Subdirectory
        run: cd algebra-laravel-ispit

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-scripts
        working-directory: ./algebra-laravel-ispit

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --coverage-text
        working-directory: ./algebra-laravel-ispit

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
        working-directory: ./algebra-laravel-ispit
